# google-dkim.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Google DKIM DNS record'

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the DKIM record
  DKIMValue:
    Type: String
    Description: The DKIM value provided by Google

Resources:
  DKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref DomainName
      Name: !Sub 'google._domainkey.${DomainName}'
      Type: TXT
      TTL: '300'
      ResourceRecords:
        - !Sub '"${DKIMValue}"'
