AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 DNS records for CloudFront distribution'

Parameters:
  DomainName:
    Type: String
    Description: The domain name (e.g., example.com)
  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID
  CloudFrontDomainName:
    Type: String
    Description: The CloudFront distribution domain name
  IncludeWWW:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Whether to include www subdomain

Conditions:
  IncludeWWWDomain: !Equals [!Ref IncludeWWW, 'true']

Resources:
  ApexDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false

  WWWDomainRecord:
    Type: AWS::Route53::RecordSet
    Condition: IncludeWWWDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'www.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false

Outputs:
  ApexDomainName:
    Description: The apex domain name
    Value: !Ref DomainName
  WWWDomainName:
    Description: The www domain name
    Value: !Sub 'www.${DomainName}'
    Condition: IncludeWWWDomain
