AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 Hosted Zone for S3 static website with CloudFront integration'

Parameters:
  DomainName:
    Type: String
    Description: 'The domain name for the hosted zone (e.g., example.com)'

  DomainType:
    Type: String
    Description: 'The domain type (Basic, WWW, Wildcard, Subdomains)'
    Default: Basic

  CustomSubdomains:
    Type: String
    Description: 'If domain type is subdomains, then provide list of subdomains'
    Default: 'None'
    
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${DomainName}'
        

Outputs:
  HostedZoneId:
    Description: 'Hosted Zone ID'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'

  DomainName:
    Description: 'Domain Name'
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'

  DomainType:
    Description: 'Domain Type'
    Value: !Ref DomainType
    Export:
      Name: !Sub '${AWS::StackName}-DomainType'

  CustomSubdomains:
    Description: 'Custom Subdomains'
    Value: !Ref CustomSubdomains
    Export:
      Name: !Sub '${AWS::StackName}-CustomSubdomains'
      
  NameServers:
    Description: 'Name Servers (update these in your domain registrar)'
    Value: !Join [', ', !GetAtt HostedZone.NameServers]
