AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 DNS records for CloudFront distribution'

Parameters:
  DomainName:
    Type: String
    Description: The domain name (e.g., example.com)
  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID
  CloudFrontDomainName:
    Type: String
    Description: The CloudFront distribution domain name
  DomainType:
    Type: String
    Default: 'WWW'
    AllowedValues: ['Basic', 'WWW', 'Wildcard','Subdomain']
    Description: Domain type
  CustomSubdomain:
    Type: String
    Description: Custom subdomain for DomainType Subdomain

Conditions:
  IncludeWWWDomain: !Equals [!Ref DomainType, 'WWW']
  IsWildcard: !Equals [!Ref DomainType, 'Wildcard']
  IsSubdomain: !Equals [!Ref DomainType, 'Subdomain']
    

Resources:
  ApexDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false

  WWWDomainRecord:
    Type: AWS::Route53::RecordSet
    Condition: IncludeWWWDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'www.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false
  
  WildcardDomainRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsWildcard
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '*.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false

    WildcardDomainRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsSubdomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomSubdomain
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # This is the fixed hosted zone ID for CloudFront
        EvaluateTargetHealth: false
        

Outputs:
  ApexDomainName:
    Description: The apex domain name
    Value: !Ref DomainName
  WWWDomainName:
    Description: The www domain name
    Value: !Sub 'www.${DomainName}'
    Condition: IncludeWWWDomain
  WildcardDomainName:
    Description: The wildcard domain name
    Value: !Sub '*.${DomainName}'
    Condition: IncludeWWWDomain
