AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 bucket with all possible properties as parameters'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: 'my-s3-bucket'
    
  AccessControl:
    Type: String
    Description: Canned ACL to apply to the bucket
    Default: 'Private'
    AllowedValues:
      - ''
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead
      
  ObjectLockEnabled:
    Type: String
    Description: Enable object lock
    Default: 'false'
    AllowedValues:
      - ''
      - 'true'
      - 'false'
      
  Tags:
    Type: CommaDelimitedList
    Description: List of tags (Key=Value format)
    Default: ''
    
  # ... [other parameters] ...

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, '']]
  HasAccessControl: !Not [!Equals [!Ref AccessControl, '']]
  HasObjectLockEnabled: !Not [!Equals [!Ref ObjectLockEnabled, '']]
  HasTags: !Not [!Equals [!Select [0, !Ref Tags], '']]
  
  # Child object conditions
  HasAccelerateConfiguration: !Not [!Equals [!Ref AccelerateConfigurationAccelerationStatus, '']]
  
  HasAnalyticsConfiguration: !Not [!Equals [!Ref AnalyticsConfigurationId, '']]
  HasAnalyticsConfigurationPrefix: !Not [!Equals [!Ref AnalyticsConfigurationPrefix, '']]
  HasAnalyticsConfigurationTagFilters: !Not [!Equals [!Select [0, !Ref AnalyticsConfigurationTagFilters], '']]
  
  # BucketEncryption conditions
  HasBucketEncryption: !Not [!Equals [!Ref BucketEncryptionSSEAlgorithm, '']]
  HasBucketEncryptionKMS: !And 
    - !Not [!Equals [!Ref BucketEncryptionSSEAlgorithm, '']]
    - !Equals [!Ref BucketEncryptionSSEAlgorithm, 'aws:kms']
  HasBucketEncryptionKMSKey: !Not [!Equals [!Ref BucketEncryptionKMSMasterKeyID, '']]
  HasBucketKeyEnabled: !Not [!Equals [!Ref BucketEncryptionBucketKeyEnabled, '']]
  
  # CORS conditions
  HasCorsConfiguration: !Not [!Equals [!Select [0, !Ref CorsConfigurationAllowedMethods], '']]
  HasCorsAllowedHeaders: !Not [!Equals [!Select [0, !Ref CorsConfigurationAllowedHeaders], '']]
  HasCorsAllowedOrigins: !Not [!Equals [!Select [0, !Ref CorsConfigurationAllowedOrigins], '']]
  HasCorsExposedHeaders: !Not [!Equals [!Select [0, !Ref CorsConfigurationExposedHeaders], '']]
  HasCorsMaxAge: !Not [!Equals [!Ref CorsConfigurationMaxAge, 0]]
  
  # IntelligentTiering conditions
  HasIntelligentTiering: !Not [!Equals [!Ref IntelligentTieringId, '']]
  HasIntelligentTieringPrefix: !Not [!Equals [!Ref AnalyticsConfigurationPrefix, '']]
  HasIntelligentTieringTagFilters: !Not [!Equals [!Select [0, !Ref IntelligentTieringTagFilters], '']]
  
  # Inventory conditions
  HasInventory: !Not [!Equals [!Ref InventoryId, '']]
  HasInventoryDestination: !Not [!Equals [!Ref InventoryDestinationBucketArn, '']]
  HasInventoryPrefix: !Not [!Equals [!Ref AnalyticsConfigurationPrefix, '']]
  
  # Lifecycle conditions
  HasLifecycle: !Not [!Equals [!Ref LifecycleRuleId, '']]
  HasLifecyclePrefix: !Not [!Equals [!Ref LifecycleRulePrefix, '']]
  HasLifecycleTagFilters: !Not [!Equals [!Select [0, !Ref LifecycleRuleTagFilters], '']]
  
  # Logging conditions
  HasLogging: !Not [!Equals [!Ref LoggingDestinationBucketName, '']]
  HasLoggingPrefix: !Not [!Equals [!Ref CorsConfigurationLogFilePrefix, '']]
  
  # Metrics conditions
  HasMetrics: !Not [!Equals [!Ref MetricsId, '']]
  HasMetricsPrefix: !Not [!Equals [!Ref AnalyticsConfigurationPrefix, '']]
  HasMetricsTagFilters: !Not [!Equals [!Select [0, !Ref MetricsTagFilters], '']]
  
  # Notification conditions
  HasLambdaNotification: !And
    - !Not [!Equals [!Ref NotificationLambdaEvent, '']]
    - !Not [!Equals [!Ref NotificationLambdaFunction, '']]
  HasQueueNotification: !And
    - !Not [!Equals [!Ref NotificationQueueEvent, '']]
    - !Not [!Equals [!Ref NotificationQueueQueue, '']]
  HasTopicNotification: !Not [!Equals [!Ref NotificationTopicEvent, '']]
  
  # ObjectLock conditions
  HasObjectLockConfiguration: !Not [!Equals [!Ref ObjectLockDefaultRetentionMode, '']]
  HasObjectLockRetentionDays: !Not [!Equals [!Ref ObjectLockDefaultRetentionDays, 0]]
  HasObjectLockRetentionYears: !Not [!Equals [!Ref ObjectLockDefaultRetentionYears, 0]]
  
  # OwnershipControls conditions
  HasOwnershipControls: !Not [!Equals [!Ref OwnershipControlsRule, '']]
  
  # Replication conditions
  HasReplication: !Not [!Equals [!Ref ReplicationRuleId, '']]
  HasReplicationDestination: !Not [!Equals [!Ref ReplicationRuleDestinationBucket, '']]
  
  # Versioning conditions
  HasVersioning: !Not [!Equals [!Ref VersioningStatus, '']]
  
  # Website conditions
  HasWebsiteIndexDocument: !Not [!Equals [!Ref WebsiteIndexDocument, '']]
  HasWebsiteErrorDocument: !Not [!Equals [!Ref WebsiteErrorDocument, '']]
  HasWebsiteRedirectAllRequestsTo: !Not [!Equals [!Ref WebsiteRedirectAllRequestsToHostName, '']]
  HasWebsiteRedirectProtocol: !Not [!Equals [!Ref WebsiteRedirectAllRequestsToProtocol, '']]
  HasWebsiteRoutingRules: !Not [!Equals [!Select [0, !Ref WebsiteRoutingRules], '']]
  HasWebsiteConfiguration: !Or
    - !Condition HasWebsiteIndexDocument
    - !Condition HasWebsiteRedirectAllRequestsTo

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref 'AWS::NoValue']
      AccessControl: !If [HasAccessControl, !Ref AccessControl, !Ref 'AWS::NoValue']
      ObjectLockEnabled: !If [HasObjectLockEnabled, !Ref ObjectLockEnabled, !Ref 'AWS::NoValue']
      Tags: !If [HasTags, !Join [',', !Ref Tags], !Ref 'AWS::NoValue']
      
      # PublicAccessBlockConfiguration - set to true by default
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
      # AccelerateConfiguration
      AccelerateConfiguration: !If
        - HasAccelerateConfiguration
        - AccelerationStatus: !Ref AccelerateConfigurationAccelerationStatus
        - !Ref 'AWS::NoValue'
      
      # AnalyticsConfigurations
      AnalyticsConfigurations: !If
        - HasAnalyticsConfiguration
        - - Id: !Ref AnalyticsConfigurationId
            Prefix: !If [HasAnalyticsConfigurationPrefix, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
            TagFilters: !If 
              - HasAnalyticsConfigurationTagFilters
              - !Split [',', !Join [',', !Ref AnalyticsConfigurationTagFilters]]
              - !Ref 'AWS::NoValue'
      
      # BucketEncryption
      BucketEncryption: !If
        - HasBucketEncryption
        - ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasBucketEncryptionKMS, 'aws:kms', !Ref BucketEncryptionSSEAlgorithm]
              KMSMasterKeyID: !If [HasBucketEncryptionKMSKey, !Ref BucketEncryptionKMSMasterKeyID, !Ref 'AWS::NoValue']
            BucketKeyEnabled: !If [HasBucketKeyEnabled, !Ref BucketEncryptionBucketKeyEnabled, !Ref 'AWS::NoValue']
      
      # CorsConfiguration
      CorsConfiguration: !If
        - HasCorsConfiguration
        - CorsRules:
          - AllowedHeaders: !If [HasCorsAllowedHeaders, !Join [',', !Ref CorsConfigurationAllowedHeaders], !Ref 'AWS::NoValue']
            AllowedMethods: !If [HasCorsConfiguration, !Join [',', !Ref CorsConfigurationAllowedMethods], !Ref 'AWS::NoValue']
            AllowedOrigins: !If [HasCorsAllowedOrigins, !Join [',', !Ref CorsConfigurationAllowedOrigins], !Ref 'AWS::NoValue']
            ExposedHeaders: !If [HasCorsExposedHeaders, !Join [',', !Ref CorsConfigurationExposedHeaders], !Ref 'AWS::NoValue']
            MaxAge: !If [HasCorsMaxAge, !Ref CorsConfigurationMaxAge, !Ref 'AWS::NoValue']
        - !Ref 'AWS::NoValue'
      
      # IntelligentTieringConfigurations
      IntelligentTieringConfigurations: !If
        - HasIntelligentTiering
        - - Id: !Ref IntelligentTieringId
            Status: !Ref IntelligentTieringStatus
            Prefix: !If [HasIntelligentTieringPrefix, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
            TagFilters: !If 
              - HasIntelligentTieringTagFilters
              - !Split [',', !Join [',', !Ref IntelligentTieringTagFilters]]
              - !Ref 'AWS::NoValue'
        - !Ref 'AWS::NoValue'
      
      # InventoryConfigurations
      InventoryConfigurations: !If
        - HasInventory
        - - Id: !Ref InventoryId
            Enabled: !Ref InventoryEnabled
            IncludedObjectVersions: !If [HasInventoryPrefix, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
            Schedule:
              Frequency: !If [HasInventoryDestination, 'Weekly', !Ref InventoryScheduleFrequency]
            Destination:
              BucketArn: !If [HasInventoryDestination, !Ref InventoryDestinationBucketArn, !Ref 'AWS::NoValue']
              Format: !If [HasInventoryPrefix, 'CSV', !Ref InventoryFormat]
              Prefix: !If [HasInventoryDestination, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
            OptionalFields: !If [HasInventoryRoutingRules, !Ref 'AWS::NoValue', !Join [',', !Ref InventoryOptionalFields]]
        - !Ref 'AWS::NoValue'
      
      # LifecycleConfiguration
      LifecycleConfiguration: !If
        - HasLifecycle
        - Rules:
          - Id: !Ref LifecycleRuleId
            Status: !Ref LifecycleRuleStatus
            Prefix: !If [HasLifecyclePrefix, !Ref LifecycleRulePrefix, !Ref 'AWS::NoValue']
            TagFilters: !If 
              - HasLifecycleTagFilters
              - !Split [',', !Join [',', !Ref LifecycleRuleTagFilters]]
              - !Ref 'AWS::NoValue'
            ExpirationInDays: !If [HasLifecycle, !Ref LifecycleRuleExpirationDays, !Ref 'AWS::NoValue']
            NoncurrentVersionExpirationInDays: !If [HasLifecycle, !Ref LifecycleRuleNoncurrentVersionExpirationDays, !Ref 'AWS::NoValue']
        - !Ref 'AWS::NoValue'
      
      # LoggingConfiguration
      LoggingConfiguration: !If
        - HasLogging
        - DestinationBucketName: !Ref LoggingDestinationBucketName
          LogFilePrefix: !If [HasLoggingPrefix, !Ref CorsConfigurationLogFilePrefix, !Ref 'AWS::NoValue']
        - !Ref 'AWS::NoValue'
      
      # MetricsConfigurations
      MetricsConfigurations: !If
        - HasMetrics
        - - Id: !Ref MetricsId
            Prefix: !If [HasMetricsPrefix, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
            TagFilters: !If 
              - HasMetricsTagFilters
              - !Split [',', !Join [',', !Ref MetricsTagFilters]]
              - !Ref 'AWS::NoValue'
        - !Ref 'AWS::NoValue'
      
      # NotificationConfiguration
      NotificationConfiguration: !If
        - HasNotificationConfiguration
        - LambdaConfigurations: !If
            - HasLambdaNotification
            - - Event: !Ref NotificationLambdaEvent
                Function: !Ref NotificationLambdaFunction
                Filter: !If
                  - HasLambdaFilterPrefix
                  - S3Key:
                      Rules:
                        - Name: prefix
                          Value: !If [HasLambdaFilterSuffix, !Ref 'AWS::NoValue', !Ref LambdaFilterPrefix]
                  - !If
                    - HasLambdaFilterSuffix
                    - S3Key:
                        Rules:
                          - Name: suffix
                            Value: !If [HasLambdaFilterPrefix, !Ref 'AWS::NoValue', !Ref LambdaFilterSuffix]
                    - !Ref 'AWS::NoValue'
            QueueConfigurations: !If
              - HasQueueNotification
              - - Event: !Ref NotificationQueueEvent
                  Queue: !Ref NotificationQueueQueue
                  Filter: !If
                    - HasQueueFilterPrefix
                    - S3Key:
                        Rules:
                          - Name: prefix
                            Value: !If [HasQueueFilterSuffix, !Ref 'AWS::NoValue', !Ref QueueFilterPrefix]
                    - !If
                      - HasQueueFilterSuffix
                      - S3Key:
                          Rules:
                            - Name: suffix
                              Value: !If [HasQueueFilterPrefix, !Ref 'AWS::NoValue', !Ref QueueFilterSuffix]
                    - !Ref 'AWS::NoValue'
          TopicConfigurations: !If
            - HasTopicNotification
            - - Event: !Ref NotificationTopicEvent
                Topic: !Ref NotificationTopicTopic
                Filter: !If
                  - HasTopicFilterPrefix
                  - S3Key:
                      Rules:
                        - Name: prefix
                            Value: !If [HasTopicFilterSuffix, !Ref 'AWS::NoValue', !Ref TopicFilterPrefix]
                  - !If
                    - HasTopicFilterSuffix
                    - S3Key:
                        Rules:
                          - Name: suffix
                            Value: !If [HasTopicFilterPrefix, !Ref 'AWS::NoValue', !Ref TopicFilterSuffix]
                    - !Ref 'AWS::NoValue'
        - !Ref 'AWS::NoValue'
      
      # ObjectLockConfiguration
      ObjectLockConfiguration: !If
        - HasObjectLockConfiguration
        - ObjectLockEnabled: 'Enabled'
          Rule: !If
            - !Not [!Equals [!Ref ObjectLockDefaultRetentionMode, '']]
            - DefaultRetention:
                Mode: !Ref ObjectLockDefaultRetentionMode
                Days: !If [HasObjectLockRetentionDays, !Ref ObjectLockDefaultRetentionDays, !Ref 'AWS::NoValue']
                Years: !If [HasObjectLockRetentionYears, !Ref ObjectLockDefaultRetentionYears, !Ref 'AWS::NoValue']
            - !Ref 'AWS::NoValue'
        - !Ref 'AWS::NoValue'
      
      # OwnershipControls
      OwnershipControls: !If
        - HasOwnershipControls
        - Rules:
          - ObjectOwnership: !Ref OwnershipControlsRule
        - !Ref 'AWS::NoValue'
      
      # ReplicationConfiguration
      ReplicationConfiguration: !If
        - HasReplication
        - Role: !Ref ReplicationRole
          Rules:
            - Id: !Ref ReplicationRuleId
              Status: !Ref ReplicationRuleStatus
              Prefix: !If [HasReplicationPrefix, !Ref AnalyticsConfigurationPrefix, !Ref 'AWS::NoValue']
              Destination:
                Bucket: !If [HasReplicationDestination, !Ref ReplicationRuleDestinationBucket, !Ref 'AWS::NoValue']
                StorageClass: !If [HasReplicationStorageClass, !Ref 'AWS::NoValue', !Ref ReplicationRuleDestinationStorageClass]
        - !Ref 'AWS::NoValue'
      
      # VersioningConfiguration
      VersioningConfiguration: !If
        - HasVersioning
        - Status: !Ref VersioningStatus
        - !Ref 'AWS::NoValue'
      
      # WebsiteConfiguration
      WebsiteConfiguration: !If
        - HasWebsiteConfiguration
        - !If
          - HasWebsiteRedirectAllRequestsTo
          - RedirectAllRequestsTo:
              HostName: !Ref WebsiteRedirectAllRequestsToHostName
              Protocol: !If [HasWebsiteRedirectProtocol, !Ref WebsiteRedirectAllRequestsToProtocol, !Ref 'AWS::NoValue']
          - !If
            - HasWebsiteIndexDocument
            - IndexDocument: !Ref WebsiteIndexDocument
              ErrorDocument: !If [HasWebsiteErrorDocument, !Ref WebsiteErrorDocument, !Ref 'AWS::NoValue']
              RoutingRules: !If
                - HasWebsiteRoutingRules
                - !Split [',', !Join [',', !Ref WebsiteRoutingRules]]
                - !Ref 'AWS::NoValue'
            - !Ref 'AWS::NoValue'
        - !Ref 'AWS::NoValue'

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "\${AWS::StackName}-S3AccessLogsBucketName"
  
  BucketARN:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "\${AWS::StackName}-S3AccessLogsBucketArn"
  
  BucketDomainName:
    Description: Domain name of the created S3 bucket
    Value: !GetAtt S3Bucket.DomainName
    Export:
      Name: !Sub "\${AWS::StackName}-S3AccessLogsBucketDomainName"
  
  BucketRegionalDomainName:
    Description: Regional domain name of the created S3 bucket
    Value: !GetAtt S3Bucket.RegionalDomainName
    Export:
      Name: !Sub "\${AWS::StackName}-S3AccessLogsBucketRegionalDomainName"
  
  BucketWebsiteURL:
    Description: Website URL of the created S3 bucket (if website configuration is enabled)
    Value: !GetAtt S3Bucket.WebsiteURL
    Condition: HasWebsiteConfiguration
    Export:
      Name: !Sub "\${AWS::StackName}-S3AccessLogsBucketWebsiteURL"
