AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for ACM certificate DNS validation record (CNAME)'

Parameters:
  HostedZoneId:
    Type: String
    Description: 'The ID of the hosted zone where the DNS record will be created'

  DomainName:
    Type: String
    Description: 'The domain name for the certificate'
    
  RecordName:
    Type: String
    Description: 'The name of the validation record'
    
  RecordValue:
    Type: String
    Description: 'The value of the validation record'

Resources:
  ValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RecordName
      Type: 'CNAME'
      TTL: '300'
      ResourceRecords:
        - !Ref RecordValue

Outputs:
  DomainName:
    Description: 'Domain name for the certificate'
    Value: !Ref DomainName
  
  ValidationRecordName:
    Description: 'Name of the validation record'
    Value: !Ref RecordName
  
  ValidationRecordType:
    Description: 'Type of the validation record'
    Value: 'CNAME'


