AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate with DNS Validation'

Parameters:
  DomainName:
    Type: String
    Description: 'The domain name for the certificate'
  
  CertificateType:
    Type: String
    AllowedValues: [Basic, WWW, Wildcard, CustomSubdomains]
    Default: WWW
    Description: 'Type of certificate to create'
  
  ValidationMethod:
    Type: String
    AllowedValues: [DNS, EMAIL]
    Default: DNS
    Description: 'Method to validate domain ownership'
  
  CustomSubdomains:
    Type: String
    Description: 'Comma-separated list of subdomains (only for CustomSubdomains type)'
    Default: ''

Conditions:
  IsBasicCertificate: !Equals [!Ref CertificateType, 'Basic']
  IsWWWCertificate: !Equals [!Ref CertificateType, 'WWW']
  IsWildcardCertificate: !Equals [!Ref CertificateType, 'Wildcard']
  IsCustomCertificate: !Equals [!Ref CertificateType, 'CustomSubdomains']

Resources:
  # Basic Certificate (domain only)
  BasicCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsBasicCertificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: !Ref ValidationMethod
  
  # Certificate with www subdomain
  WWWCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsWWWCertificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      ValidationMethod: !Ref ValidationMethod
  
  # Wildcard Certificate
  WildcardCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsWildcardCertificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: !Ref ValidationMethod
  
  # Custom Subdomains Certificate
  CustomCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: IsCustomCertificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: !Split [',', !Ref CustomSubdomains]
      ValidationMethod: !Ref ValidationMethod

Outputs:
  CertificateArn:
    Description: 'ARN of the created certificate'
    Value: !If
      - IsBasicCertificate
      - !Ref BasicCertificate
      - !If
        - IsWWWCertificate
        - !Ref WWWCertificate
        - !If
          - IsWildcardCertificate
          - !Ref WildcardCertificate
          - !Ref CustomCertificate

