AWSTemplateFormatVersion: '2010-09-09'
Description: 'Update Name Servers for Route 53 Domain'

Parameters:
  DomainName:
    Type: String
    Description: 'The domain name to update (e.g., example.com)'
  HostedZoneId:
    Type: String
    Description: 'The ID of the hosted zone (e.g., Z1234567890ABC)'
  NameServers:
    Type: String
    Description: 'Comma-separated list of name servers WITHOUT trailing dots (e.g., ns-1234.awsdns-56.org,ns-789.awsdns-12.com)'

Resources:
  NameServersRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: NS
      TTL: '172800'
      ResourceRecords:
        Fn::Split:
          - ","
          - Fn::Join:
              - ","
              - Fn::Transform:
                  Name: AWS::Include
                  Parameters:
                    Location: !Sub |
                      #set($nameservers = $NameServers.split(","))
                      #set($result = [])
                      #foreach($ns in $nameservers)
                      #set($void = $result.add("${ns}."))
                      #end
                      $result

Outputs:
  UpdatedDomain:
    Description: 'Domain with updated name servers'
    Value: !Ref DomainName
  NameServers:
    Description: 'Configured name servers (with dots added)'
    Value: !Join [", ", !Split [",", !Ref NameServers]]
