AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an IAM user with password stored in Secrets Manager'

Parameters:
  Username:
    Type: String
    Description: Name for the IAM user
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "^[a-zA-Z0-9+=,.@_-]+$"
    ConstraintDescription: Must be a valid IAM username
  
  KmsKeyArn:
    Type: String
    Description: ARN of the KMS key to use for encrypting the secret
    AllowedPattern: "^arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[a-f0-9-]+$"
    ConstraintDescription: Must be a valid KMS key ARN
    
  AdditionalPrincipalArn:
    Type: String
    Description: ARN of an additional principal (user/role) who should have access to the secret
    AllowedPattern: "^(arn:aws:iam::[0-9]{12}:(user|role)/[a-zA-Z0-9+=,.@_/-]+)?$"
    ConstraintDescription: Must be a valid IAM user or role ARN, or left empty

Conditions:
  HasAdditionalPrincipal: !Not [!Equals [!Ref AdditionalPrincipalArn, ""]]

Resources:
  GeneratedPassword:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref Username
      Description: !Sub "Password for IAM user ${Username}"
      KmsKeyId: !Ref KmsKeyArn
      GenerateSecretString:
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true
        SecretStringTemplate: '{"username": "${Username}"}'
        GenerateStringKey: "password"

  # Resource policy with conditional additional principal
  SecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref GeneratedPassword
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/${Username}'
                - !If [HasAdditionalPrincipal, !Ref AdditionalPrincipalArn, !Ref "AWS::NoValue"]
            Action:
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'secretsmanager:*'
            Resource: '*'

  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref Username
      Path: "/"
      LoginProfile:
        Password: !Join ['', ['{{resolve:secretsmanager:', !Ref GeneratedPassword, ':SecretString:password}}' ]]
        PasswordResetRequired: true

Outputs:
  UserName:
    Description: Name of the created IAM user
    Value: !Ref MyIAMUser
  
  SecretName:
    Description: Name of the secret containing the user's password
    Value: !Ref GeneratedPassword
  
  SecretEncryptionKey:
    Description: KMS key used to encrypt the secret
    Value: !Ref KmsKeyArn
  
  AdditionalAccessPrincipal:
    Description: Additional principal with access to the secret
    Value: !If [HasAdditionalPrincipal, !Ref AdditionalPrincipalArn, "None"]

