AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an IAM user with a temporary password in AWS Secrets Manager'

Parameters:
  Username:
    Type: String
    Description: Name for the IAM user
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z0-9+=,.@_-]+"
    ConstraintDescription: Must be a valid IAM username
  
  KmsKeyArn:
    Type: String
    Description: ARN of the KMS key to use for encrypting the secret
    AllowedPattern: "arn:aws:kms:[a-z0-9-]+:[0-9]{12}:key/[a-f0-9-]+"
    ConstraintDescription: Must be a valid KMS key ARN
  
  AdditionalPrincipalArn:
    Type: String
    Description: ARN of an additional principal (user/role) who should have access to the secret
    AllowedPattern: "^(arn:aws:iam::[0-9]{12}:(user|role)/[a-zA-Z0-9+=,.@_/-]+|arn:aws:iam::[0-9]{12}:root)?$"
    ConstraintDescription: Must be a valid IAM user or role ARN, root user ARN, or left empty

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Username
      Path: /
      Tags:
        - Key: CreatedBy
          Value: CloudFormation

  # Generate a random password for the user
  RandomPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Username}-temp-password"
      Description: !Sub "Temporary password for IAM user ${Username}"
      KmsKeyId: !Ref KmsKeyArn
      GenerateSecretString:
        SecretStringTemplate: '{"username": "${Username}"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true

  # Create login profile with the generated password
  UserLoginProfile:
    Type: AWS::IAM::UserLoginProfile
    Properties:
      UserName: !Ref User
      Password: !Join ['', ['{{resolve:secretsmanager:', !Ref RandomPassword, ':SecretString:password}}' ]]
      PasswordResetRequired: true

  SecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref RandomPassword
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !GetAtt User.Arn
              

