AWSTemplateFormatVersion: '2010-09-09'
Description: 'ACM Certificate'

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the certificate
  
  IncludeWWW:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Whether to include www subdomain
  
  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID

Conditions:
  IncludeWWWDomain: !Equals [!Ref IncludeWWW, 'true']

Resources:
  # Certificate with www
  CertificateWithWWW:
    Type: AWS::CertificateManager::Certificate
    Condition: IncludeWWWDomain
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
  
  # Certificate without www
  CertificateNoWWW:
    Type: AWS::CertificateManager::Certificate
    Condition: !Not [!Condition IncludeWWWDomain]
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Description: The ARN of the certificate
    Value: !If
      - IncludeWWWDomain
      - !Ref CertificateWithWWW
      - !Ref CertificateNoWWW
